package com.soaplat.cmsmgr.EncryptService.localhost;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Mon Jan 11 17:39:05 CST 2010
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://localhost/", name = "TaskManagerSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskManagerSoap {

    @RequestWrapper(localName = "GetAllTask", targetNamespace = "http://localhost/", className = "localhost.GetAllTask")
    @ResponseWrapper(localName = "GetAllTaskResponse", targetNamespace = "http://localhost/", className = "localhost.GetAllTaskResponse")
    @WebMethod(operationName = "GetAllTask", action = "http://localhost/GetAllTask")
    public void getAllTask(
        @WebParam(mode = WebParam.Mode.OUT, name = "GetAllTaskResult", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Integer> getAllTaskResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "nNumber", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Integer> nNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "taskIds", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<ArrayOfUnsignedInt> taskIds
    );

    @RequestWrapper(localName = "AddTask", targetNamespace = "http://localhost/", className = "localhost.AddTask")
    @ResponseWrapper(localName = "AddTaskResponse", targetNamespace = "http://localhost/", className = "localhost.AddTaskResponse")
    @WebMethod(operationName = "AddTask", action = "http://localhost/AddTask")
    public void addTask(
        @WebParam(name = "taskId", targetNamespace = "http://localhost/")
        long taskId,
        @WebParam(name = "taskPrio", targetNamespace = "http://localhost/")
        short taskPrio,
        @WebParam(name = "taskContent", targetNamespace = "http://localhost/")
        byte[] taskContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "AddTaskResult", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Integer> addTaskResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "errMsg", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.String> errMsg
    );

    @RequestWrapper(localName = "RemoveTask", targetNamespace = "http://localhost/", className = "localhost.RemoveTask")
    @ResponseWrapper(localName = "RemoveTaskResponse", targetNamespace = "http://localhost/", className = "localhost.RemoveTaskResponse")
    @WebMethod(operationName = "RemoveTask", action = "http://localhost/RemoveTask")
    public void removeTask(
        @WebParam(name = "taskId", targetNamespace = "http://localhost/")
        long taskId,
        @WebParam(mode = WebParam.Mode.OUT, name = "RemoveTaskResult", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Integer> removeTaskResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "errMsg", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.String> errMsg
    );

    @RequestWrapper(localName = "GetTaskStatus", targetNamespace = "http://localhost/", className = "localhost.GetTaskStatus")
    @ResponseWrapper(localName = "GetTaskStatusResponse", targetNamespace = "http://localhost/", className = "localhost.GetTaskStatusResponse")
    @WebMethod(operationName = "GetTaskStatus", action = "http://localhost/GetTaskStatus")
    public void getTaskStatus(
        @WebParam(name = "taskId", targetNamespace = "http://localhost/")
        long taskId,
        @WebParam(mode = WebParam.Mode.OUT, name = "GetTaskStatusResult", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Integer> getTaskStatusResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "addTime", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.String> addTime,
        @WebParam(mode = WebParam.Mode.OUT, name = "prio", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Short> prio,
        @WebParam(mode = WebParam.Mode.OUT, name = "state", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.Integer> state,
        @WebParam(mode = WebParam.Mode.OUT, name = "scIp", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.String> scIp,
        @WebParam(mode = WebParam.Mode.OUT, name = "errMsg", targetNamespace = "http://localhost/")
        javax.xml.ws.Holder<java.lang.String> errMsg
    );
}
