{
        "ACTORS": "甄子丹 赵薇 吴尊",
        "CA": 0,
        "COUNTRYDIST": "中国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "明朝时期，皇家亲军锦衣卫侍卫青龙，因发现锦衣卫杀害忠良、勾结奸臣并企图谋反的阴谋而遭到追杀，后终联手正义人士阻击，使其阴谋未能得逞......",
        "DIRECTOR": "李仁港",
        "FILENAME": "dy-jinyw.ts",
        "ISSUEDATE": "2010",
        "LANGUAGE": "中",
        "LENGTHTC": "01:48:15",
        "POSTER": "dy-jinyw.png",
        "PRODUCTNAME": "锦衣卫",
        "PROGTYPE": "古装/动作",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "6.48",
        "StarGrade": "5",
        "TITLEBRIEF": "锦衣卫",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "周润发 陈建斌 周迅",
        "CA": 0,
        "COUNTRYDIST": "中国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "公元前六世纪，屹立数百年的周室王朝已朝不保夕，各诸侯国割据一方，为了达到称霸的目的而相互征战。这是中国历史上一个气势磅礴的时代，一个辉煌灿烂的时代。在这个时代中，有战争、有英雄，有思想、有著作......中国史称为\"春秋\"时代。",
        "DIRECTOR": "胡玫",
        "FILENAME": "dy-kongz.ts",
        "ISSUEDATE": "2010",
        "LANGUAGE": "中",
        "LENGTHTC": "02:00:15",
        "POSTER": "dy-kongz.png",
        "PRODUCTNAME": "孔子",
        "PROGTYPE": "古装/传记",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "7.19",
        "StarGrade": "5",
        "TITLEBRIEF": "孔子",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "周迅 张涵予 李冰冰",
        "CA": 0,
        "COUNTRYDIST": "中国",
        "CopyrightNUMB": "ISRC CN-M66-09-0010-0/V.J9",
        "CopyrightOwner": "华录",
        "DESCRIPTION": "日军及伪政府的高级将领屡遭暗杀，日军头领武田判断，只有内部情报已遭泄露的情况下，这些抗日杀手才能屡次得手，司令部藏有一位代号为＂老鬼＂的共产党，而＂老鬼＂在不知行动泄露的情况下，依然发出了错误的情报。武田在截获这份情报后，将汪伪政府直属单位＂华北剿匪司令部＂ 五个情报人员骗到了封闭的裘庄，展开调查。谁才是真正的＂老鬼＂？短兵相接明争暗斗之后，谁又能够最终逃出裘庄？",
        "DIRECTOR": "高群书 陈国富",
        "FILENAME": "dy-fengs.ts",
        "ISSUEDATE": "2009",
        "LANGUAGE": "",
        "LENGTHTC": "",
        "POSTER": "dy-fengs.png",
        "PRODUCTNAME": "风声",
        "PROGTYPE": "惊悚/犯罪",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "17.5",
        "StarGrade": "5",
        "TITLEBRIEF": "风声",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "小罗伯特.唐尼 裘德.洛 瑞秋.麦克亚当斯",
        "CA": 0,
        "COUNTRYDIST": "美国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "因使用黑魔法而被处绞刑的布莱克伍德公爵居然＂死而复生＂，而且还利用人们的恐惧兴风作浪，福尔摩斯和华生决心查出真相......",
        "DIRECTOR": "盖.里奇",
        "FILENAME": "dy-daztfems.ts",
        "ISSUEDATE": "2009",
        "LANGUAGE": "英",
        "LENGTHTC": "02:03:11",
        "POSTER": "dy-daztfems.png",
        "PRODUCTNAME": "大侦探福尔摩斯",
        "PROGTYPE": "悬疑/动作",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "中SRT",
        "SUMFILESIZE": "7.38",
        "StarGrade": "5",
        "TITLEBRIEF": "大侦探福尔摩斯",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "薛景求 河智苑 朴重勋",
        "CA": 0,
        "COUNTRYDIST": "韩国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "海云台海滩距离釜山市中心11公里，是韩国最有名的海水温泉浴场。某年夏天的海云台海滨，人山人海。就在这个夏天一场剧烈的海啸袭来。灾难中，游客们妻离子散，海水侵没了一切......",
        "DIRECTOR": "尹济均",
        "FILENAME": "dy-haiyt.ts",
        "ISSUEDATE": "2009",
        "LANGUAGE": "韩",
        "LENGTHTC": "01:55:25",
        "POSTER": "dy-haiyt.png",
        "PRODUCTNAME": "海云台",
        "PROGTYPE": "灾难",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "中SRT",
        "SUMFILESIZE": "6.91",
        "StarGrade": "5",
        "TITLEBRIEF": "海云台",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "小沈阳 孙红雷 闫妮",
        "CA": 0,
        "COUNTRYDIST": "中国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "遥远的大漠中，风云变幻，充满着紧张的气氛。＂麻子面馆＂老板王五麻子是一个恶贯满盈、吝啬的＂大漠周扒皮＂。如此老板，其妻子老板娘经常遭到王五麻子的虐待。期待自由的老板娘与外表俊朗的店小二李四发生私情，不想却被杀手张三发现......",
        "DIRECTOR": "张艺谋",
        "FILENAME": "dy-sanqpajq.ts",
        "ISSUEDATE": "2009",
        "LANGUAGE": "中",
        "LENGTHTC": "01:34:10",
        "POSTER": "dy-sanqpajq.png",
        "PRODUCTNAME": "三枪拍案惊奇",
        "PROGTYPE": "喜剧/惊悚",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "8.35",
        "StarGrade": "5",
        "TITLEBRIEF": "三枪拍案惊奇",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "安妮.海瑟薇 帕特里克.威尔森 大卫.摩斯",
        "CA": 0,
        "COUNTRYDIST": "美国",
        "CopyrightNUMB": "ISRC CNF180904300",
        "CopyrightOwner": "华录",
        "DESCRIPTION": "精神治疗医师克莱尔日前接到一项工作，负责平复5名病人受伤的心。奇怪的是他们乘坐的飞机失事坠毁，机上所有乘客都死了，唯独他们没事，最多受了点小伤。其中男乘客埃里克最让她费心。埃里克年轻英俊，经历了这场灾难后，肉体竟然没受任何伤，而且他的表现似乎在刻意掩藏这场灾难对他心灵造成的伤害。克莱尔与埃里克几天的接触后，发现这个男人具有看透她内心的能力，两人越走越近，即将发展成男女朋友关系时，奇怪的事情发生了......",
        "DIRECTOR": "罗德里格.加齐亚",
        "FILENAME": "dy-weixfx.ts",
        "ISSUEDATE": "2008",
        "LANGUAGE": "",
        "LENGTHTC": "",
        "POSTER": "dy-weixfx.png",
        "PRODUCTNAME": "危险飞行",
        "PROGTYPE": "恐怖",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "12.1",
        "StarGrade": "4",
        "TITLEBRIEF": "危险飞行",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "甄子丹 黎明 陈慧琳",
        "CA": 0,
        "COUNTRYDIST": "中国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "在诸侯割据，战火连天的年代，甄子丹饰演的大将军慕容雪虎负责训练公主燕飞儿武功，后来公主被奸臣胡霸所害，随即逃出皇宫，幸得一位武功高强的隐士段兰泉所救，二人随即产生爱情，在隐士的帮助下，公主除掉了杀害父王的奸臣，并且夺回了王座。就在此时，公主却选择与隐士回归山林，为了爱情抛弃了大好江山。",
        "DIRECTOR": "程小东",
        "FILENAME": "dy-jiangsmr.ts",
        "ISSUEDATE": "2008",
        "LANGUAGE": "中",
        "LENGTHTC": "01:30:44",
        "POSTER": "dy-jiangsmr.png",
        "PRODUCTNAME": "江山美人",
        "PROGTYPE": "古装/动作",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "7.97",
        "StarGrade": "",
        "TITLEBRIEF": "江山美人",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "绫濑遥 小出惠介 阿井莉沙",
        "CA": 0,
        "COUNTRYDIST": "日本",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "次郎是个寂寞的大学生，到了生日也没人为他祝福。次郎跑到百货公司给自己买二十岁生日的礼物，碰到了一个好像刚从火灾现场逃出来的可爱女孩，女孩挑了件连衣裙，没付钱就扬长而去。接着，次郎在餐厅独自吃饭时，又碰到了她。女孩拉着次郎一起庆祝生日。次郎被搞得团团转，还被她打，两人因为吃霸王餐给警察狂追......",
        "DIRECTOR": "郭在容",
        "FILENAME": "dy-wodjqrny.ts",
        "ISSUEDATE": "2008",
        "LANGUAGE": "日",
        "LENGTHTC": "02:00:43",
        "POSTER": "dy-wodjqrny.png",
        "PRODUCTNAME": "我的机器人女友",
        "PROGTYPE": "喜剧/爱情/科幻",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "中SRT",
        "SUMFILESIZE": "7.23",
        "StarGrade": "5",
        "TITLEBRIEF": "我的机器人女友",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "杰瑞米.雷纳 安东尼.麦凯 布莱恩.格拉格提",
        "CA": 0,
        "COUNTRYDIST": "美国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "伊拉克反叛武装和驻伊美军之间的残酷斗争，就像是在玩着一场旷日持久的猫鼠游戏。本片就是讲述了一组美国拆弹专家被派往巴格达执行任务，在那里每个当地人都像是潜在的敌人，每一个目标都像是伪装的炸弹，他们必须小心翼翼，稍不留神就会付出生命的代价......",
        "DIRECTOR": "凯瑟琳.毕格罗",
        "FILENAME": "dy-chaidbd.ts",
        "ISSUEDATE": "2008",
        "LANGUAGE": "英",
        "LENGTHTC": "02:05:45",
        "POSTER": "dy-chaidbd.png",
        "PRODUCTNAME": "拆弹部队",
        "PROGTYPE": "战争/动作",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "中SRT",
        "SUMFILESIZE": "7.53",
        "StarGrade": "5",
        "TITLEBRIEF": "拆弹部队",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "林嘉欣 黄磊 陆毅",
        "CA": 0,
        "COUNTRYDIST": "中国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "女人奔三，对另一半的每个选择都像是在一个三叉路口，向左行还是向右行？聂冰遇上了十二个型男，哪一型才是自己的归宿呢？",
        "DIRECTOR": "张建亚",
        "FILENAME": "dy-aiqhjzy2.ts",
        "ISSUEDATE": "2008",
        "LANGUAGE": "中",
        "LENGTHTC": "01:47:25",
        "POSTER": "dy-aiqhjzy2.png",
        "PRODUCTNAME": "爱情呼叫转移2",
        "PROGTYPE": "爱情/喜剧",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "6.43",
        "StarGrade": "4",
        "TITLEBRIEF": "爱情呼叫转移2",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "罗伯特.帕特里克 乔什.哈切森 安娜.索暮亚.罗伯",
        "CA": 0,
        "COUNTRYDIST": "美国",
        "CopyrightNUMB": "ISRC CNC070900150",
        "CopyrightOwner": "华录",
        "DESCRIPTION": "十一岁的小男孩吉斯一直梦想能成为学校中跑得最快的学生，正当他赢得了年级里的田径冠军之时，一个叫莱斯莉的小女孩突然地出现，成了他在田径场上的劲敌。似乎跑得比任何人都快的转学来的学生莱斯莉是个挺神秘的人物。逐渐认识她的同学告诉别人，在莱斯莉的家里居然没有电视，整个屋子都堆满了各种各样的书籍。热情好交友的吉斯很快与大方善谈的莱斯莉成了好朋友。之后的一天，莱斯莉告诉吉斯一个秘密......",
        "DIRECTOR": "嘉柏.丘波",
        "FILENAME": "dy-xianjzq.ts",
        "ISSUEDATE": "2007",
        "LANGUAGE": "",
        "LENGTHTC": "",
        "POSTER": "dy-xianjzq.png",
        "PRODUCTNAME": "仙境之桥",
        "PROGTYPE": "奇幻/家庭/冒险",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "13.1",
        "StarGrade": "5",
        "TITLEBRIEF": "仙境之桥",
        "VideoBitrate": ""
    },
    {
        "ACTORS": "希亚.拉博夫 梅根.福克斯 乔什.杜哈明",
        "CA": 0,
        "COUNTRYDIST": "美国",
        "CopyrightNUMB": "",
        "CopyrightOwner": "文广",
        "DESCRIPTION": "地球上的战争虽然结束，但变形金刚之间的战争并未告终。红蜘蛛飞回塞博坦星球，打算带着军队再回到地球一决死战。汽车人发现威震天的尸体不见了，原来已被萨克巨人偷走，威震天随后被复活，决心要开始复仇......",
        "DIRECTOR": "迈克尔.贝",
        "FILENAME": "dy-bianxjg1.ts",
        "ISSUEDATE": "2007",
        "LANGUAGE": "",
        "LENGTHTC": "",
        "POSTER": "dy-bianxjg1.png",
        "PRODUCTNAME": "变形金刚1",
        "PROGTYPE": "科幻/动作",
        "QualityGrade": "",
        "SUBSCRIBERETIME": "",
        "SUBTITLELANGUAGE": "",
        "SUMFILESIZE": "8.27",
        "StarGrade": "5",
        "TITLEBRIEF": "变形金刚1",
        "VideoBitrate": ""
    }
