package com.srmmgr.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Nov 20 13:55:08 CST 2009
 * Generated source version: 2.2.3
 * 
 */
 
@WebService(targetNamespace = "http://webservice.srmmgr.com/", name = "IProgProductRelWS")
@XmlSeeAlso({ObjectFactory.class})
public interface IProgProductRelWS {

    @ResponseWrapper(localName = "getAllProgProductRelResponse", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.GetAllProgProductRelResponse")
    @RequestWrapper(localName = "getAllProgProductRel", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.GetAllProgProductRel")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public java.util.List<java.lang.Object> getAllProgProductRel();

    @ResponseWrapper(localName = "saveProgProductRelResponse", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.SaveProgProductRelResponse")
    @RequestWrapper(localName = "saveProgProductRel", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.SaveProgProductRel")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public int saveProgProductRel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.srmmgr.webservice.ProgProductRel> arg0
    );

    @ResponseWrapper(localName = "updateProgProductRelResponse", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.UpdateProgProductRelResponse")
    @RequestWrapper(localName = "updateProgProductRel", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.UpdateProgProductRel")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public int updateProgProductRel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.srmmgr.webservice.ProgProductRel> arg0
    );

    @ResponseWrapper(localName = "deleteProgProductRelResponse", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.DeleteProgProductRelResponse")
    @RequestWrapper(localName = "deleteProgProductRel", targetNamespace = "http://webservice.srmmgr.com/", className = "com.srmmgr.webservice.DeleteProgProductRel")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod
    public int deleteProgProductRel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.srmmgr.webservice.ProgProductRel> arg0
    );
}
