
/*
 * 
 */

package com.srmmgr.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Nov 20 13:55:08 CST 2009
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "ProgProductRelWSService", 
                  wsdlLocation = "file:/D:/wsdl/WSProgProductRelService.wsdl",
                  targetNamespace = "http://webservice.srmmgr.com/") 
public class ProgProductRelWSService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.srmmgr.com/", "ProgProductRelWSService");
    public final static QName ProgProductRelWSPort = new QName("http://webservice.srmmgr.com/", "ProgProductRelWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/wsdl/WSProgProductRelService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/wsdl/WSProgProductRelService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ProgProductRelWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProgProductRelWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProgProductRelWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IProgProductRelWS
     */
    @WebEndpoint(name = "ProgProductRelWSPort")
    public IProgProductRelWS getProgProductRelWSPort() {
        return super.getPort(ProgProductRelWSPort, IProgProductRelWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProgProductRelWS
     */
    @WebEndpoint(name = "ProgProductRelWSPort")
    public IProgProductRelWS getProgProductRelWSPort(WebServiceFeature... features) {
        return super.getPort(ProgProductRelWSPort, IProgProductRelWS.class, features);
    }

}
