
/*
 * 
 */

package com.srmmgr.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.2.3
 * Fri Nov 20 13:40:51 CST 2009
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "StbCustomerWSService", 
                  wsdlLocation = "file:/D:/wsdl/WSStbCustomerService.wsdl",
                  targetNamespace = "http://webservice.srmmgr.com/") 
public class StbCustomerWSService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webservice.srmmgr.com/", "StbCustomerWSService");
    public final static QName StbCustomerWSPort = new QName("http://webservice.srmmgr.com/", "StbCustomerWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/wsdl/WSStbCustomerService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/D:/wsdl/WSStbCustomerService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public StbCustomerWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StbCustomerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StbCustomerWSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns IStbCustomerWS
     */
    @WebEndpoint(name = "StbCustomerWSPort")
    public IStbCustomerWS getStbCustomerWSPort() {
        return super.getPort(StbCustomerWSPort, IStbCustomerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStbCustomerWS
     */
    @WebEndpoint(name = "StbCustomerWSPort")
    public IStbCustomerWS getStbCustomerWSPort(WebServiceFeature... features) {
        return super.getPort(StbCustomerWSPort, IStbCustomerWS.class, features);
    }

}
